### ISSUE TITLE
Update npm version

### ISSUE THREAD

**Issue by ruessej** [kewisch/sepa.js#44]
@kewisch  Are there any plans to release the current version to npm?

**Comment by kewisch** [comment]
There are a few easy enhancements in the issue list that I'd love to incorporate, but I hope I find time to release as well.

**Comment by teeleh** [comment]
Hi Kewisch, would it be possible to package your code up into one package and publish on https://unpkg.com/ ? You can easily do this (according to them) using the following instructions:

Workflow
For npm package authors, unpkg relieves the burden of publishing your code to a CDN in addition to the npm registry. All you need to do is include your [UMD](https://github.com/umdjs/umd) build in your npm package (not your repo, that's different!).

You can do this easily using the following setup:

Add the umd (or dist) directory to your .gitignore file
Add the umd directory to your [files array](https://docs.npmjs.com/files/package.json#files) in package.json
Use a build script to generate your UMD build in the umd directory when you publish
That's it! Now when you npm publish you'll have a version available on unpkg as well.

Thanks a lot !

**Comment by kewisch** [comment]
I'm not using any build scripts. Does https://unpkg.com/browse/sepa.js@0.8.0/lib/sepa.min.js work for you?

**Comment by teeleh** [comment]
Hi Phillip,

Thank you for your quick response. I would like to use your library in a tool we use to build a back office application: www.retool.com<http://www.retool.com>

I tried your unpkg link, but Retool does not like it:

[Graphical user interface, text, application, email  Description automatically generated]

In Retool it is not possible to use require() and everything should be riding in one package. Here is the response to a similar question:

“For JS library imports we support files that contain the entire library. The link you tried has imports to other files and so that won’t work.”

I don’t know how to do that (put it all one package). Here is an example of another library that had the same problem trying to get it to run in Retool.com (the Question and the Answer to the solution:

Q: Trying to load this module following the instructions in the docs: ***@***.***/index.min.js
But I’m not able to call it in a Retool JS query or JS transformer. Any thoughts?

CONTENT:
/**
* Minified by jsDelivr using UglifyJS v3.4.4.
* Original file: ***@***.******@***.***/index.js>
*  Do NOT use SRI with dynamically generated files! More information: https://www.jsdelivr.com/using-sri-with-dynamic-files
*/
"use strict";module.exports=require("./lib/index");

A: You need to use ***@***.***/dist/shortid-2.2.13.min.js which has all code in one package.

My question to you is if you know how to get sepa-xml into one package like above, I guess you have the experience to do this quite quickly.

Thank you so much for your time, Teele Horstra

From: Philipp Kewisch ***@***.***>
Reply to: "kewisch/sepa.js" ***@***.***>
Date: Wednesday, 25 January 2023 at 14:33
To: "kewisch/sepa.js" ***@***.***>
Cc: Teele Horstra | YARD ***@***.***>, Comment ***@***.***>
Subject: Re: [kewisch/sepa.js] Update npm version (Issue #44)


I'm not using any build scripts. Does ***@***.***/lib/sepa.min.js work for you?

**Comment by kewisch** [comment]
Ah I see. Filed https://github.com/kewisch/sepa.js/issues/47 for this

**Comment by danieldiekmeier** [comment]
Thank you for the package, @kewisch! Would you consider releasing the latest commit from `main` as 1.0.4, maybe? The dependency on `xmldom` leads to security warnings in `npm audit`. For me, it would be very helpful if you released it, even if you didn't include any other changes for now.

**Comment by kewisch** [comment]
Done, hope it works well!

**Comment by danieldiekmeier** [comment]
Thank you!
